version: '3.8'

services:
  food-portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: food-portfolio-dev
    restart: unless-stopped
    ports:
      - "3000:3000"  # Frontend
      - "5000:5000"  # Backend API
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - dev_logs:/app/logs
    networks:
      - food-portfolio-dev-network
    command: npm run dev:full

volumes:
  dev_logs:
    driver: local

networks:
  food-portfolio-dev-network:
    driver: bridge